Aplikacija/MNP_main/Controllers/DeliveryController.cs
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MNP_main.Controllers
{
    [Authorize(Roles = "DeliveryGuy")]
    public class DeliveryController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        private readonly AspNetUserManager<User> _userManager;

        public DeliveryController(IOrderService orderService, IUserService userService, AspNetUserManager<User> userManager)
        {
            _orderService = orderService;
            _userService = userService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUserByIdAsync(_userManager.GetUserId(User));
            return View("Index", user.OrdersToDeliver.Where(x => !x.Delivered).ToList());
        }
        
        public async Task<IActionResult> Deliver([FromRoute(Name = "id")] int id)
        {
            await _orderService.Deliver(id);
            return await Index();
        }
    }
}

Aplikacija/MNP_main/Controllers/OrderController.cs
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MNP_main.Models;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MNP_main.Controllers
{
    [Authorize(Roles = "Worker,Admin")]
    public class OrderController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private readonly IOrderService _orderService;
        private readonly AspNetUserManager<User> _userManager;


        public OrderController(ILogger<UserController> logger, IUserService userService, IOrderService order, AspNetUserManager<User> userManager)
        {
            this._logger = logger;
            this._userService = userService;
            this._orderService = order;
            this._userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> OrderHistory()
        {
            var korisnik = await _userManager.GetUserAsync(User);
            var orders = (await _userService.GetUserByIdAsync(korisnik.Id)).Orders.ToList();
            return View(orders.Select(o => new OrderViewModel(o)).ToList());
        }

        public async Task<IActionResult> OrderManagement()
        {
            List<OrderViewModel> viewOrders = new List<OrderViewModel>();
            List<Order> orders = await _orderService.GetAllOrdersAsync();
            orders.ForEach(o => {
                OrderViewModel ord = new OrderViewModel();
                ord.Id = o.Id.ToString();
                ord.SpecialRequest = o.SpecialRequest;
                ord.Price = o.Price.ToString();
                ord.OrderDate = o.OrderDate;
                ord.DeliveryDate = o.DeliveryDate;
                ord.Client = o.Client;
                ord.Deliverer = o.Deliverer;
                viewOrders.Add(ord);
            });
            return View("OrderManagement", viewOrders);
        }

        [AllowAnonymous]
        public async Task<IActionResult> OrderInformation()
        {
            ViewBag.deliveryGuys = (List<User>)(await _userManager.GetUsersInRoleAsync("DeliveryGuy"));

            int id = int.Parse(Request.RouteValues["Id"].ToString());
            Order o = await _orderService.GetOrderById(id);
            return View("OrderInformation", new OrderViewModel()
            {
                Id = o.Id.ToString(),
                SpecialRequest = o.SpecialRequest,
                Price = o.Price.ToString(),
                OrderDate = o.OrderDate,
                DeliveryDate = o.DeliveryDate,
                Client = o.Client,
                Breakfast = o.Breakfast,
                Lunch = o.Lunch,
                Dinner = o.Dinner
            });
        }

        [HttpPost]
        public async Task<IActionResult> OrderConfirmed(string Id, string IdOrder)
        {
            User deliverer = await _userService.GetUserByIdAsync(Id);
            Order order = await _orderService.GetOrderById(int.Parse(IdOrder));
            await _orderService.SetDeliveryGuyAsync(order.Id, deliverer.Id);
            return await OrderManagement();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Aplikacija/MNP_main/Controllers/UsersController.cs
using DAL.Models;
using BLL.Interfaces;
using BLL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MNP_main.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MNP_main.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IUserService _userService;
        private readonly ICommentService _commentService;
        private readonly IOrderService _orderService;

        public UsersController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, IUserService userService, ICommentService commentService, IOrderService orderService)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this._userService = userService;
            this._commentService = commentService;
            this._orderService = orderService;
        }

        public IActionResult Index() => View(userManager.Users.ToList());
        public IActionResult Return() => View("Index", userManager.Users.ToList());

        [HttpPost]
        public async Task<IActionResult> CreateUser([FromForm] UserViewModel user)
        {
            if (user.Password != user.ConfirmPassword)
                return View("Error", "Password and ConfirmPassword must match.");

            var newUser = new User
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                PhoneNumber = user.PhoneNumber,
                CardNumber = user.CardNumber,
                Email = user.Email,
                UserName = user.UserName,
                UMCN = user.UCMN,
                EmailConfirmed = true
            };

            var result = await userManager.CreateAsync(newUser, user.Password);

            if (await roleManager.RoleExistsAsync(user.Role))
                await userManager.AddToRoleAsync(newUser, user.Role);

            if (result.Succeeded)
                return View("Index", userManager.Users.ToList());

            return View("Error", result.Errors.Select(x => x.Description).ToArray());
        }

        public async Task<IActionResult> EditUser()
        {
            string Id = Request.RouteValues["Id"].ToString();

            User u = await _userService.GetUserByIdAsync(Id);

            return View("EditUser", u);
        }

        public async Task<IActionResult> DeleteUser()
        {
            string Id = Request.RouteValues["Id"].ToString();

            User u = await _userService.GetUserByIdAsync(Id);

            List<Comment> comments = await _commentService.GetAllCommentsFromUser(u);
            for (int i=0; i<comments.Count; ++i)
                await _commentService.RemoveComment(comments[i].Id);

            List<Order> orders = (await _orderService.GetAllOrdersAsync()).Where(x => x.Client.Id == u.Id).ToList();
            for (int i = 0; i < orders.Count; ++i)
                await _orderService.RemoveOrder(orders[i].Id);

            await userManager.DeleteAsync(u);

            return View("Index", userManager.Users.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> ChangeUser([FromForm] UserViewModel user)
        {
            User u = await userManager.FindByIdAsync(user.Id);


            if (user.Password != null)
            {
                if (user.Password != user.ConfirmPassword)
                    return View("Error", new string[] { "Password and ConfirmPassword must match." });

                await userManager.RemovePasswordAsync(u);
                await userManager.AddPasswordAsync(u, user.Password);
            }

            if (user.FirstName != null)
            {
                u.FirstName = user.FirstName;
            }

            if (user.LastName != null)
            {
                u.LastName = user.LastName;
            }

            if (user.Address != null)
            {
                u.Address = user.Address;
            }

            if (user.PhoneNumber != null)
            {
                u.PhoneNumber = user.PhoneNumber;
            }

            if (user.CardNumber != null)
            {
                u.CardNumber = user.CardNumber;
            }

            if (user.Email != null)
            {
                u.Email = user.Email;
                u.EmailConfirmed = true;
            }

            if (user.UserName != null)
            {
                u.UserName = user.UserName;
            }

            if (user.UCMN != null)
            {
                u.UMCN = user.UCMN;
            }

            var result = await userManager.UpdateAsync(u);


            if (result.Succeeded)
                return View("Index", userManager.Users.ToList());

            return View("Error", result.Errors.Select(x => x.Description).ToArray());
        }
    }
}

Aplikacija/MNP_main/Views/Shared/_BreakfastPartial.cshtml
@model Menu
@using Microsoft.AspNetCore.Http
@using DAL.Models;

@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    string selectedFood = Context.Session.GetString("selectedFood") ?? "";
    var selectedIds = selectedFood.Split(',').Where(x => int.TryParse(x, out _)).Select(x => int.Parse(x));

    var foods = Model.Foods;

    var orderFoods = foods.Where(x => selectedIds.Contains(x.Id)).ToList();

    Food breakfastMain = orderFoods.Find(x => x.Meal == Food.MealType.Breakfast && x.Type == Food.DishType.Main);
    Food breakfastDesert = orderFoods.Find(x => x.Meal == Food.MealType.Breakfast && x.Type == Food.DishType.Desert);
}

<!-- DORUČAK -->
<div class="container">

    <div class="row d-flex flex-column justify-content-center align-items-center">
        <h1 class="menu-meal text-center">@Localizer["Breakfast"]</h1>
    </div>

    <!-- CONTAINER KARTICA-->
    <div class="row">
        <!-- KARTICA ZA HRANU -->
        <div class="col-lg-6 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-1.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (breakfastMain == null)
                    {
                        <h4 class="card-title">@Localizer["Main meal"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose main meal."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@breakfastMain.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 0,
                            dishType = 0
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>
        <!-- END OF KARTICA ZA HRANU -->

        <div class="col-lg-6 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-2.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (breakfastDesert == null)
                    {
                        <h4 class="card-title">@Localizer["Beverage"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose beverage."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@breakfastDesert.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 0,
                            dishType = 3
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>
    </div>
    <!-- END OF CONTAINER KARTICA -->
</div>
<!-- END OF DO DORUČAK-->

Aplikacija/MNP_main/Views/Shared/_DinnerPartial.cshtml
@using DAL.Models;
@using Microsoft.AspNetCore.Http
@model Menu
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    string selectedFood = Context.Session.GetString("selectedFood") ?? "";
    var selectedIds = selectedFood.Split(',').Where(x => int.TryParse(x, out _)).Select(x => int.Parse(x));

    var foods = Model.Foods;

    var orderFoods = foods.Where(x => selectedIds.Contains(x.Id)).ToList();

    Food dinnerMain = orderFoods.Find(x => x.Meal == Food.MealType.Dinner && x.Type == Food.DishType.Main);
    Food dinnerSalad = orderFoods.Find(x => x.Meal == Food.MealType.Dinner && x.Type == Food.DishType.Salad);
    Food dinnerDesert = orderFoods.Find(x => x.Meal == Food.MealType.Dinner && x.Type == Food.DishType.Desert);
}

<!-- VEČERA -->
<div class="container">
    <div class="row d-flex flex-column justify-content-center align-items-center">
        <h1 class="menu-meal text-center">@Localizer["Dinner"]</h1>
    </div>

    <div class="row">
        <div class="col-lg-4 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-1.jpg" alt="Card image cap">
                <div class="card-body">
                    @if(dinnerMain == null)
                    { 
                    <h4 class="card-title">@Localizer["Main meal"]</h4>
                    <p class="card-text text-center">
                        @Localizer["Choose main meal."]
                    </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@dinnerMain.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 2,
                            dishType = 0
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>

        <div class="col-lg-4 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-2.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (dinnerSalad == null)
                    {
                        <h4 class="card-title">@Localizer["Salad"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose salad."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@dinnerSalad.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 2,
                            dishType = 2
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>

        <div class="col-lg-4 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-3.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (dinnerDesert == null)
                    {
                        <h4 class="card-title">@Localizer["Dessert"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose dessert."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@dinnerDesert.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 2,
                            dishType = 3
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END OF VEČERA -->

Aplikacija/MNP_main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="initial-scale=1.0">
	<title>@ViewData["Title"] - MNP</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer;
	<link rel="stylesheet" href="~/css/AddFood.css" />
</head>
<body style="overflow-x:hidden">
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light text-white mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
					<img src="~/img/logo.png" width="50" height="50" alt="">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Worker") || User.IsInRole("Admin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Food" asp-action="AddFood">@Localizer["Add food"]</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Menu" asp-action="EditMenu">@Localizer["Edit menu"]</a>
                            </li>
                        }


                        @if (User.Identity.IsAuthenticated && User.IsInRole("Worker"))
                        {
                            <li>
                                <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="OrderManagement">@Localizer["Order Management"]</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Users" asp-action="Index">@Localizer["Manage users"]</a>
                                </li>
                            }

                            @if (User.IsInRole("DeliveryGuy"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Delivery" asp-action="Index">@Localizer["Deliver Orders"]</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="ShowComments">@Localizer["Comments"]</a>
                        </li>

                    </ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>

	<span>
		<img src="~/img/logo.png" alt="Alternate Text" style="position:absolute; margin-left:5%;" width="150px" height="150px" />
	</span>

	<div class="container">
		<main role="main" class="pb-2">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="row justify-content-between px-5">
			<div class="col-md-5">
				&copy; 2021 - Quickpix
			</div>
			<div class="col-md-5 text-right">
				@await Html.PartialAsync("_SelectLanguagePartial")
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Aplikacija/MNP_main/Views/Shared/_LunchPartial.cshtml
@using DAL.Models;
@using Microsoft.AspNetCore.Http
@model Menu
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    string selectedFood = Context.Session.GetString("selectedFood") ?? "";
    var selectedIds = selectedFood.Split(',').Where(x => int.TryParse(x, out _)).Select(x => int.Parse(x));

    var foods = Model.Foods;

    var orderFoods = foods.Where(x => selectedIds.Contains(x.Id)).ToList();

    Food lunchMain = orderFoods.Find(x => x.Meal == Food.MealType.Lunch && x.Type == Food.DishType.Main);
    Food lunchSoup = orderFoods.Find(x => x.Meal == Food.MealType.Lunch && x.Type == Food.DishType.Soup);
    Food lunchSalad = orderFoods.Find(x => x.Meal == Food.MealType.Lunch && x.Type == Food.DishType.Salad);
    Food lunchDesert = orderFoods.Find(x => x.Meal == Food.MealType.Lunch && x.Type == Food.DishType.Desert);
}

<!-- RUČAK -->
<div class="container">
    <div class="row d-flex flex-column justify-content-center align-items-center">
        <h1 class="menu-meal text-center">@Localizer["Lunch"]</h1>
    </div>

    <div class="row">
        <div class="col-lg-3 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-3.jpg" alt="Card image cap">
                <div class="card-body">
                    @if(lunchMain == null)
                    {
                        <h4 class="card-title">@Localizer["Main meal"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose main meal."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@lunchMain.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 1,
                            dishType = 0
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>

        <div class="col-lg-3 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-1.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (lunchSoup == null)
                    {
                        <h4 class="card-title">@Localizer["Soup"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose soup."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@lunchSoup.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 1,
                            dishType = 1
                        },
                        new { @class = "btn btn-primary" }
                    )
                    </div>
            </div>
        </div>

        <div class="col-lg-3 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-2.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (lunchSalad == null)
                    {
                        <h4 class="card-title">@Localizer["Salad"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose salad."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@lunchSalad.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 1,
                            dishType = 2
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>

        <div class="col-lg-3 p-2">
            <div class="card text-center">
                <img class="card-img-top" src="../img/food-3.jpg" alt="Card image cap">
                <div class="card-body">
                    @if (lunchDesert == null)
                    {
                        <h4 class="card-title">@Localizer["Dessert"]</h4>
                        <p class="card-text text-center">
                            @Localizer["Choose dessert."]
                        </p>
                    }
                    else
                    {
                        <h4 class="menu-meal">@lunchDesert.Name</h4>
                    }
                    @Html.ActionLink(
                        Localizer["Choose"].Value,
                        "SelectFood",
                        "Food",
                        routeValues: new
                        {
                            mealType = 1,
                            dishType = 3
                        },
                        new { @class = "btn btn-primary" }
                    )
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END OF DORUČAK -->

Aplikacija/MNP_main/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    LocOptions.Value.SupportedUICultures = new List<System.Globalization.CultureInfo>
    {
        new System.Globalization.CultureInfo("en-US"),
        new System.Globalization.CultureInfo("sr-Latn-RS")
    };

    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" 
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" 
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
          onchange="this.form.submit();"
          asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>